export const SOLANA_WALLET_REGEX = /^[1-9A-HJ-NP-Za-km-z]{32,44}$/;
export const REFERRAL_CODE_PREFIX = 'REF-';
export const REFERRAL_CODE_LENGTH = 8;
export const REFERRAL_CODE_CHARSET = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ';
export const REFERRAL_MAX_BATCH_SIZE = 200;
